name: Publish to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build
      
      - name: Run tests
        run: npm test --if-present
      
      - name: Check if version changed
        id: version-check
        run: |
          PUBLISHED_VERSION=$(npm view three-cluster-lights version || echo "0.0.0")
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          if [ "$PUBLISHED_VERSION" != "$LOCAL_VERSION" ]; then
            echo "VERSION_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Publish to npm
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}